# Generated by Django 4.2 on 2026-05-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('lorry_no', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=50)),
                ('no_of_boxes', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_at', models.CharField(blank=True, max_length=200)),
                ('no_of_articles', models.PositiveIntegerField(blank=True, null=True)),
                ('approx_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('service_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_clerk', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignee_vouchers', to='transport.party')),
                ('consigner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consigner_vouchers', to='transport.party')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.route')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
