# Generated by Django 4.2 on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_stop_deliveryvoucher_from_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.AddField(
            model_name='route',
            name='from_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='transport.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='to_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='transport.stop'),
        ),
    ]
