# Generated by Django 4.2 on 2026-05-29

from django.db import migrations, models


def copy_route_endpoints_to_stops(apps, schema_editor):
    Route = apps.get_model('transport', 'Route')
    for route in Route.objects.all():
        stop_ids = [stop_id for stop_id in [route.from_stop_id, route.to_stop_id] if stop_id]
        if stop_ids:
            route.stops.add(*stop_ids)


def clear_route_stops(apps, schema_editor):
    Route = apps.get_model('transport', 'Route')
    for route in Route.objects.all():
        route.stops.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_route_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='routes', to='transport.stop'),
        ),
        migrations.RunPython(copy_route_endpoints_to_stops, clear_route_stops),
    ]
