# Generated by Django 4.2 on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_route_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryvoucher',
            name='lorry_no',
        ),
    ]
