# Generated by Django 4.2 on 2026-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_deliveryvoucher_lorry_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KAP TRANSPORTS', max_length=200)),
                ('address_line_1', models.CharField(default='3/776, Panikar Road', max_length=200)),
                ('address_line_2', models.CharField(default='Kozhikode, Kerala - 673011', max_length=200)),
                ('gst_no', models.CharField(default='32EMOPP4910C1Z7', max_length=30)),
                ('mobile_1', models.CharField(default='9446635069', max_length=20)),
                ('mobile_2', models.CharField(blank=True, default='9400107632', max_length=20)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.AddField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('consigner', 'Consigner'), ('consignee', 'Consignee'), ('both', 'Consigner & Consignee')], default='both', max_length=20),
        ),
    ]
