# Generated by Django 4.2.30 on 2026-06-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_companyprofile_party_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address_line_1',
            field=models.CharField(default='Address_line1_here', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_line_2',
            field=models.CharField(default='Address_line 2_here', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gst_no',
            field=models.CharField(default='gst_number_here', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='mobile_1',
            field=models.CharField(default='mobile_no_1 here', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='mobile_2',
            field=models.CharField(blank=True, default='mobile_number_2 here', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='TRANSPORTS COMPANY_name here', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryvoucher',
            name='to_pay',
            field=models.DecimalField(decimal_places=2, default=101, max_digits=10),
            preserve_default=False,
        ),
    ]
