# Generated by Django 4.2.30 on 2026-06-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_companyprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvoucher',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
