# Generated by Django 4.2.30 on 2026-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_deliveryvoucher_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryvoucher',
            name='no_of_boxes',
            field=models.PositiveIntegerField(),
        ),
    ]
