# Generated by Django 4.2.30 on 2026-07-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_deliveryvoucher_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvoucher',
            name='to_pay',
            field=models.BooleanField(default=True, help_text='True = To Pay, False = Paid'),
        ),
    ]
