# Generated by Django 4.2.30 on 2026-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_deliveryvoucher_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvoucher',
            name='signed_image',
            field=models.ImageField(blank=True, help_text='Upload signed delivery voucher image', null=True, upload_to='signed_vouchers/'),
        ),
    ]
