# Generated by Django 4.2.30 on 2026-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_deliveryvoucher_signed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvoucher',
            name='signed_image',
            field=models.FileField(blank=True, help_text='Upload signed delivery voucher image or PDF', null=True, upload_to='signed_vouchers/'),
        ),
    ]
