# Generated by Django 4.2.30 on 2026-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_deliveryvoucher_signed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvoucher',
            name='auto_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryvoucher',
            name='extra_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
